[project]
name = "cv"
version = "0.1.0"
description = "Gijs Molenaar's CV built with RenderCV"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-pptx>=1.0.2",
    "rendercv[full]>=2.0",
]
